-----------------------PROCEDIMIENTOS AGREGADOS,FUNCIONES,TRIGGERS---------------------------------------
USE PROYECTOF3
GO

--AGREGAR O ACTUALIZAR UN ESTUDIANTE 
GO
 CREATE OR ALTER PROCEDURE SP_INSERTAR_O_ACTUALIZAR_ESTUDIANTE(@ID_ESTUDIANTE varchar(9),
												@NOMBRE_ESTUDIANTE varchar(25),
												@APELLIDO1 varchar(20),
												@APELLIDO2 varchar(20),
												@TELEFONO varchar(8),
												@CORREO varchar(30),
												@PROVINCIA varchar(10),
												@CANTON varchar(25),
												@DISTRITO varchar(25),
												@FECHA_INGRESO date,
												@ESTADO varchar(3),
												@MSJ varchar(100)OUT) 
AS
	BEGIN TRY
		BEGIN TRAN
			IF(NOT EXISTS(SELECT 1 FROM ESTUDIANTES WHERE ID_ESTUDIANTE=@ID_ESTUDIANTE))
				BEGIN
					INSERT INTO ESTUDIANTES (ID_ESTUDIANTE,NOMBRE_ESTUDIANTE,APELLIDO1_ESTUDIANTE,APELLIDO2_ESTUDIANTE,
											TELEFONO_ESTUDIANTE,CORREO_ESTUDIANTE,PROVINCIA_ESTUDIANTE,CANTON_ESTUDIANTE,
											DISTRITO_ESTUDIANTE,FECHA_INGRESO_ESTUDIANTE,ESTADO_ESTUDIANTE)
									 VALUES(@ID_ESTUDIANTE,@NOMBRE_ESTUDIANTE,@APELLIDO1,@APELLIDO2,@TELEFONO,@CORREO
											,@PROVINCIA,@CANTON,@DISTRITO,@FECHA_INGRESO,@ESTADO)
					SET @MSJ = 'SE AGREGO CORRECTAMENTE'
					
				END
			ELSE
				BEGIN
					UPDATE ESTUDIANTES SET 	NOMBRE_ESTUDIANTE=@NOMBRE_ESTUDIANTE,
											APELLIDO1_ESTUDIANTE=@APELLIDO1,
											APELLIDO2_ESTUDIANTE=@APELLIDO2,
											TELEFONO_ESTUDIANTE=@TELEFONO,
											CORREO_ESTUDIANTE=@CORREO,
											PROVINCIA_ESTUDIANTE=@PROVINCIA,
											CANTON_ESTUDIANTE=@CANTON,
											DISTRITO_ESTUDIANTE=@DISTRITO,
											FECHA_INGRESO_ESTUDIANTE=@FECHA_INGRESO,
											ESTADO_ESTUDIANTE=@ESTADO											
											WHERE ID_ESTUDIANTE=@ID_ESTUDIANTE

					SET @MSJ='SE ACTUALIZO CORRECTAMENTE'
				END
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN 
		SET @MSJ=ERROR_MESSAGE()
	END CATCH

GO
--SELECT * FROM PROFESORES


--DECLARE @ID_ESTUDIANTE varchar(9) = '333333333'
--DECLARE @NOMBRE_ESTUDIANTE varchar(25) = 'JUANITO'
--DECLARE @APELLIDO1 varchar(20) = 'HURTADO'
--DECLARE @APELLIDO2 varchar(20) = 'HURTADO'
--DECLARE @TELEFONO varchar(8) = '65566556'
--DECLARE @CORREO varchar(30) = 'JUANITO@GMAIL.COM'
--DECLARE @PROVINCIA varchar(10) = 'PUNTARENAS'
--DECLARE @CANTON varchar(25) = 'ESPARZA'
--DECLARE @DISTRITO varchar(25) = 'ESPARZA1'
--DECLARE @FECHA_INGRESO date = '20230212'
--DECLARE @ESTADO varchar(3) = 'ACT'
--DECLARE @MSJ varchar(100)

---- TODO: Set parameter values here.

--EXECUTE [dbo].[SP_INSERTAR_O_ACTUALIZAR_ESTUDIANTE] 
--   @ID_ESTUDIANTE
--  ,@NOMBRE_ESTUDIANTE
--  ,@APELLIDO1
--  ,@APELLIDO2
--  ,@TELEFONO
--  ,@CORREO
--  ,@PROVINCIA
--  ,@CANTON
--  ,@DISTRITO
--  ,@FECHA_INGRESO
--  ,@ESTADO  
--  ,@MSJ OUTPUT
--  PRINT @MSJ 
--GO



GO
--AGREGAR O ACTUALIZAR UN PROFESOR
CREATE OR ALTER PROCEDURE SP_AGREGAR_O_ACTUALIZAR_PROFESOR(@ID_PROFESOR varchar(9),
											 @NOMBRE_PROFESOR varchar(25),
											 @APELLIDO1_PROFESOR varchar(20),
											 @APELLIDO2_PROFESOR varchar(20),
											 @TELEFONO_PROFESOR varchar (8),
											 @CORREO_PROFESOR varchar(25),
											 @BORRADO_P bit,
											 @MSJ varchar(100)OUT)
AS
	BEGIN TRY
		BEGIN TRAN
			IF(NOT EXISTS(SELECT 1 FROM PROFESORES WHERE ID_PROFESOR = @ID_PROFESOR))
				BEGIN
					INSERT INTO PROFESORES(ID_PROFESOR,NOMBRE_PROFESOR,APELLIDO1_PROFESOR,
										  APELLIDO2_PROFESOR,TELFONO_PROFESOR,CORREO_PROFESOR,
										  BORRADO_P)
								    VALUES(@ID_PROFESOR,@NOMBRE_PROFESOR,@APELLIDO1_PROFESOR,
									       @APELLIDO2_PROFESOR,@TELEFONO_PROFESOR,@CORREO_PROFESOR,
										   @BORRADO_P)
					SET @MSJ = 'SE AGREGO CORRECTAMENTE'
				END
			ELSE
				BEGIN
					UPDATE PROFESORES SET ID_PROFESOR=@ID_PROFESOR,
										  NOMBRE_PROFESOR=@NOMBRE_PROFESOR,
										  APELLIDO1_PROFESOR=@APELLIDO1_PROFESOR,
										  APELLIDO2_PROFESOR=@APELLIDO2_PROFESOR,
										  TELFONO_PROFESOR=@TELEFONO_PROFESOR,
										  CORREO_PROFESOR=@CORREO_PROFESOR,
										  BORRADO_P=@BORRADO_P
										  WHERE ID_PROFESOR=@ID_PROFESOR
					SET @MSJ='SE ACTUALIZO CORRECTAMENTE'
				END			
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		SET @MSJ = ERROR_MESSAGE()
	END CATCH
GO

--SELECT * FROM ESTUDIANTES
----USE [PROYECTOF3]
--GO


--DECLARE @ID_PROFESOR varchar(9) = '206730046'
--DECLARE @NOMBRE_PROFESOR varchar(25) ='JUAN'
--DECLARE @APELLIDO1_PROFESOR varchar(20)='CASTRO'
--DECLARE @APELLIDO2_PROFESOR varchar(20)='CALVO'
--DECLARE @TELEFONO_PROFESOR varchar(8)='77889900'
--DECLARE @CORREO_PROFESOR varchar(25)='JUANCA@GMAIL.COM'
--DECLARE @BORRADO_P bit=1
--DECLARE @MSJ varchar(100)

-- TODO: Set parameter values here.

--EXECUTE [dbo].[SP_AGREGAR_O_ACTUALIZAR_PROFESOR] 
--   @ID_PROFESOR
--  ,@NOMBRE_PROFESOR
--  ,@APELLIDO1_PROFESOR
--  ,@APELLIDO2_PROFESOR
--  ,@TELEFONO_PROFESOR
--  ,@CORREO_PROFESOR
--  ,@BORRADO_P
--  ,@MSJ OUTPUT
--  PRINT @MSJ

--  SELECT*FROM PROFESORES

GO




GO

--VERIFICAR CHOCQUE PROFESORES
CREATE OR ALTER FUNCTION FN_CHOQUE_PROFESORES(@ID_PROFESOR int,
											  @DIA varchar(1),
											  @HORA_INICIO time,
											  @HORA_FIN time)
RETURNS INT AS
	BEGIN
		DECLARE @CONTADOR int
		DECLARE @RESULTADO int
			SELECT @CONTADOR = COUNT(*)
			FROM PROFESORES P INNER JOIN MODULOS_ABIERTOS MA
			ON P.ID_PROFESOR = MA.ID_PROFESOR
			INNER JOIN HORARIOS H
			ON MA.COD_MODULO_ABIERTO = H.COD_MODULO_ABIERTO
			WHERE DIA=@DIA AND MA.ID_PROFESOR=@ID_PROFESOR
			AND ((@HORA_INICIO>=HORA_INICIO) AND (@HORA_FIN>=HORA_FIN)
			OR (@HORA_FIN>=HORA_INICIO) AND (@HORA_FIN<=HORA_FIN)
			OR (@HORA_INICIO<= HORA_INICIO AND @HORA_FIN>= HORA_FIN))
			IF (@CONTADOR>0)
				BEGIN
					SET @RESULTADO = 1 --NO ES POSIBLE ASIGNAR UN PROFESOR
				END
			ELSE
				BEGIN
					SET @RESULTADO = 0 -- SI ES POSIBLE
				END		
		RETURN @RESULTADO
	END
GO
--DECLARE @ID_PROFESOR INT,@DIA VARCHAR(1),@HORA_INICIO TIME,@HORA_FINAL TIME,@RESULTADO INT 
--SET @ID_PROFESOR = '200000000'
--SET @DIA='L'
--SET @HORA_INICIO='00:07:00'
--SET @HORA_FINAL='00:13:00'
--SET @RESULTADO=9
--SET @RESULTADO=dbo.FN_CHOQUE_PROFESORES(@ID_PROFESOR,@DIA,@HORA_INICIO,@HORA_FINAL)
--PRINT @RESULTADO

--SELECT*FROM PROFESORES
--SELECT*FROM MODULOS_ABIERTOS
--SELECT*FROM HORARIOS



--GO
-----------------------------------------------------------------------------------------
--SELECT * FROM MODULOS_ABIERTOS 

------------------------------------------------------------------------------------------------------------------------------------------



--SELECT*FROM MODULOS_ABIERTOS







--------------------------------------------------------------------------------------------------------------------
GO
CREATE OR ALTER FUNCTION FN_VERIFICAR_CHOQUES_MATRICULA (@ID_ESTUDIANTE VARCHAR(9), @COD_MODULO_ABIERTO INT)
RETURNS int 
AS
	BEGIN
	DECLARE @EXISTE_CHOQUE int

		--Declaramos las siguientes variables para analizar el choque de horario.    
	DECLARE @FECHA_INICIO TIME, @FECHA_FIN TIME, @DIA varchar(1)    
--Declarmos un CURSOR para recorrer los registros del query siguiente.    
	DECLARE C_HORARIOS_MATERIA_MATRICULAR 
	CURSOR FOR
--Con este query vamos a extraer los horarios y el dia de la materia que el estudiante quiere matricular de la tabla HORARIOS.    
	SELECT        
	HORA_INICIO,
	HORA_FIN,
	DIA 
    FROM HORARIOS
    WHERE COD_MODULO_ABIERTO = @COD_MODULO_ABIERTO   
	--Abrimos cursor     
	OPEN C_HORARIOS_MATERIA_MATRICULAR
    --Recuperar informacion sobre el primer registro
	
	FETCH C_HORARIOS_MATERIA_MATRICULAR INTO @FECHA_INICIO, @FECHA_FIN, @DIA    
	--Iteramos los registros    
	WHILE (@@FETCH_STATUS = 0)        
	BEGIN            
	--En este query lo que hace es verificar si ya exite algun horario del estudiante que haga match con el horario de la materia que quiere matricular
		IF EXISTS (                
			SELECT 1
			FROM MATRICULAS m 
            INNER JOIN DETALLES_MATRICULAS DM
            ON M.COD_MATRICULA = DM.COD_MATRICULA 
            INNER JOIN MODULOS_ABIERTOS MA 
            ON DM.COD_MODULO_ABIERTO = MA.COD_MODULO_ABIERTO
            INNER JOIN HORARIOS H 
            ON MA.COD_MODULO_ABIERTO = H.COD_MODULO_ABIERTO
            WHERE M.ID_ESTUDIANTE = @ID_ESTUDIANTE                                    --Corresponde al estudiante que quiere matricular                
			AND H.DIA = @DIA
			AND(HORA_INICIO <=@FECHA_FIN AND HORA_FIN >=@FECHA_INICIO))
			

			BEGIN
				SET @EXISTE_CHOQUE=1	-- EXISTE CHOQUE		
			END
        ELSE 
            BEGIN  
				SET @EXISTE_CHOQUE=0     -- NO EXISTE CHOQUE				
			END
        --Continuar con el siguiente registro                   
		FETCH C_HORARIOS_MATERIA_MATRICULAR INTO @FECHA_INICIO, @FECHA_FIN, @DIA        
		END
    --Cerrar el CURSOR
	CLOSE C_HORARIOS_MATERIA_MATRICULAR
    --Liberar el CURSOR
	DEALLOCATE C_HORARIOS_MATERIA_MATRICULAR	
	RETURN @EXISTE_CHOQUE
	END
GO

--DECLARE @RESULTADO INT
--DECLARE @ID_ESTUDIANTE VARCHAR(9) = '206730045'
--DECLARE @COD_MODULO_ABIERTO INT = 5
--SET @RESULTADO = dbo.FN_VERIFICAR_CHOQUES_MATRICULA(@ID_ESTUDIANTE,@COD_MODULO_ABIERTO)
--PRINT @RESULTADO



-------------------------------------------------------------------------------------------------------
----ESTE QUERTY ME DICE LO QUE TIENE MATRICULADO
--SELECT M.COD_MATRICULA,DM.COD_DETALLE_MATRICULA,E.ID_ESTUDIANTE,NOMBRE_ESTUDIANTE,MA.COD_MODULO_ABIERTO,MP.REQUISITO,MO.NOMBRE_MODULO,M.ESTADO_FACTURA,M.TOTAL_MATRICULA,M.TOTAL_PAGADO,H.DIA,H.HORA_INICIO,H.HORA_FIN
--FROM ESTUDIANTES E INNER JOIN MATRICULAS M
--ON E.ID_ESTUDIANTE=M.ID_ESTUDIANTE
--INNER JOIN DETALLES_MATRICULAS DM
--ON M.COD_MATRICULA=DM.COD_MATRICULA
--INNER JOIN MODULOS_ABIERTOS MA
--ON DM.COD_MODULO_ABIERTO=MA.COD_MODULO_ABIERTO
--INNER JOIN MODULOS_PROGRAMAS MP
--ON MA.COD_MODULO_PROGRAMA=MP.COD_MODULO_PROGRAMA
--INNER JOIN MODULOS MO
--ON MP.COD_MODULO=MO.COD_MODULO
--INNER JOIN HORARIOS H
--ON H.COD_MODULO_ABIERTO=MA.COD_MODULO_ABIERTO
--WHERE E.ID_ESTUDIANTE='206730045'

--SELECT*FROM MATRICULAS

----ESTE QUERTY ES PARA VER LOS MODULOS ABIERTOS Y SUS HORARIOS
--SELECT MA.COD_MODULO_ABIERTO,MO.NOMBRE_MODULO,MP.REQUISITO,H.DIA,H.HORA_INICIO,H.HORA_FIN
--FROM MODULOS_ABIERTOS MA 
--INNER JOIN MODULOS_PROGRAMAS MP
--ON MA.COD_MODULO_PROGRAMA=MP.COD_MODULO_PROGRAMA
--INNER JOIN MODULOS MO
--ON MO.COD_MODULO=MP.COD_MODULO
--INNER JOIN HORARIOS H
--ON H.COD_MODULO_ABIERTO=MA.COD_MODULO_ABIERTO








--CREATE FUNCTION 	Nombre_Función  (Lista de parámetros)
--RETURNS Tipo de dato que devuelve la función 
--AS
--BEGIN
--	...líneas de código de la función
--	 RETURN retorno de la función
--END 

--luego se debe hacer el llamado de la función
-----------------------------------------------------------------------------------------------------------
GO
CREATE OR ALTER FUNCTION FN_VERIFICAR_REQUISITOS_MODULO(@ID_ESTUDIANTE VARCHAR(9),@COD_MODULO_ABIERTO INT)
RETURNS INT
AS
	BEGIN
		DECLARE @PUEDEMATRICULAR INT
		DECLARE @REQUISITO INT
		DECLARE @ESTADO VARCHAR(3)

		SET @REQUISITO =
		(SELECT  MP.REQUISITO 
		FROM MODULOS_ABIERTOS MA
		INNER JOIN MODULOS_PROGRAMAS MP
		ON MA.COD_MODULO_PROGRAMA=MP.COD_MODULO_PROGRAMA
		WHERE COD_MODULO_ABIERTO = @COD_MODULO_ABIERTO) 

		IF(@REQUISITO IS NOT NULL)
			BEGIN
				SELECT @ESTADO = RE.ESTADO
				FROM REGISTRO_NOTAS_ESTUDIANTES RE
				INNER JOIN MODULOS_ABIERTOS MA
				ON RE.COD_MODULO_ABIERTO=MA.COD_MODULO_ABIERTO
				INNER JOIN MODULOS_PROGRAMAS MP
				ON MA.COD_MODULO_PROGRAMA=MP.COD_PROGRAMA
				INNER JOIN ESTUDIANTES E
				ON E.ID_ESTUDIANTE=RE.ID_ESTUDIANTE
				WHERE E.ID_ESTUDIANTE=@ID_ESTUDIANTE AND MP.COD_MODULO = @REQUISITO


				IF(@ESTADO ='APR')
					BEGIN
						SET @PUEDEMATRICULAR = 1 --PUEDE MATRICULAR
					END
				ELSE
					BEGIN
						SET @PUEDEMATRICULAR = 0 --NO PUEDE MATRICULAR
					END
			END
		ELSE
			BEGIN
				SET @PUEDEMATRICULAR = 1 -- NO TIENE REQUISITO Y PUEDE MATRICULAR
			END
		RETURN @PUEDEMATRICULAR
	END
GO

--DECLARE @RESULTADO INT
--DECLARE @ID_ESTUDIANTE VARCHAR(9) = '206730045'
--DECLARE @COD_MODULO_ABIERTO INT = 2
--SET @RESULTADO = dbo.FN_VERIFICAR_REQUISITOS_MODULO(@ID_ESTUDIANTE,@COD_MODULO_ABIERTO)
--PRINT @RESULTADO

---------------------------------------------------------------------------------------------
GO
CREATE OR ALTER FUNCTION FN_VERIFCAR_MOROSO (@ID_ESTUDIANTE VARCHAR(9))
RETURNS INT
AS
	BEGIN
		DECLARE @MOROSO INT
		DECLARE @ESTADO VARCHAR(3)
		SET @ESTADO=(SELECT M.ESTADO_FACTURA
					 FROM ESTUDIANTES E 
					 INNER JOIN MATRICULAS M
					 ON E.ID_ESTUDIANTE=M.ID_ESTUDIANTE
					 WHERE E.ID_ESTUDIANTE= @ID_ESTUDIANTE)
					 
		IF(@ESTADO='PEN' OR @ESTADO = 'ANU')
			BEGIN
				SET @MOROSO=1 -- ESTA MOROSO Y NO PUEDE MATRICULAR ,ESTADO(PEN O ANU)
			END
		ELSE
			BEGIN
				SET @MOROSO=0 -- NO ESTA MOROSO PUEDE MATRICULAR, ESTADO (CAN)
			END
		RETURN @MOROSO
	END
GO
--SELECT*FROM MATRICULAS


--					SELECT M.ESTADO_FACTURA,M.COD_MATRICULA
--					 FROM ESTUDIANTES E 
--					 INNER JOIN MATRICULAS M
--					 ON E.ID_ESTUDIANTE=M.ID_ESTUDIANTE
--					 WHERE E.ID_ESTUDIANTE= '206730045'


--DECLARE @RESULTADO INT
--DECLARE @ID_ESTUDIANTE VARCHAR(9) = '206730045'
----DECLARE @COD_MODULO_ABIERTO INT = 9
--SET @RESULTADO = dbo.FN_VERIFCAR_MOROSO(@ID_ESTUDIANTE)
--PRINT @RESULTADO
----------------------------------------------------------------------------------------------
GO
CREATE OR ALTER FUNCTION FN_VERIFICA_MODULO_ABIERTO(@COD_MODULO_ABIERTO INT)
RETURNS INT
AS
	BEGIN
		DECLARE @MODULO_ABIERTO INT
		DECLARE @ESTADO_MODULO VARCHAR(3)
		SET @ESTADO_MODULO=(SELECT ESTADO
						    FROM MODULOS_ABIERTOS
						    WHERE COD_MODULO_ABIERTO=@COD_MODULO_ABIERTO)
		IF (@ESTADO_MODULO = 'ACT')
			BEGIN
				SET @MODULO_ABIERTO = 1 --EL MODULO ESTA 'ACT' ACTIVO ES MATRICULABLE
			END
		ELSE
			BEGIN
				SET @MODULO_ABIERTO = 0 --EL MODULO ESTA 'INA' INACTIVO NO ES MATRICULABLE
			END


		RETURN @MODULO_ABIERTO
	END
GO

--DECLARE @RESULTADO INT
--DECLARE @ID_ESTUDIANTE VARCHAR(9) = '206730045'
--DECLARE @COD_MODULO_ABIERTO INT = 8
--SET @RESULTADO = dbo.FN_VERIFICA_MODULO_ABIERTO(@COD_MODULO_ABIERTO)
--PRINT @RESULTADO

--SELECT*FROM MODULOS_ABIERTOS
-------------------------------------------------------------------------------------------------
--SELECT*FROM ESTUDIANTES
--SELECT*FROM MATRICULAS



--SELECT  MP.REQUISITO
--		FROM MODULOS_ABIERTOS MA
--		INNER JOIN MODULOS_PROGRAMAS MP
--		ON MA.COD_MODULO_PROGRAMA=MP.COD_MODULO_PROGRAMA
--		WHERE COD_MODULO_ABIERTO =  2

-------------------------------------
--CREATE OR ALTER PROCEDURE ()



--AS
--	BEGIN TRY
--		BEGIN TRAN
--		COMMIT TRAN
--	END TRY
--	BEGIN CATCH
--		ROLLBACK
--	END CATCH
-------------------------------------
----------------------------------------------------------------------------------------------------
GO
CREATE OR ALTER PROCEDURE SP_MATRICULAR (@ID_ESTUDIANTE varchar(9),
										 @COD_MODULO_ABIERTO int,
										 @TOTAL_PAGADO DECIMAL(10,2),
										 @MSJ varchar(1000) OUT)
AS
	BEGIN TRY
		BEGIN TRAN
			DECLARE @VERIFICA_MODULO_ABIERTO INT
			DECLARE @VERIFICA_CHOQUE_MATRICULA INT
			DECLARE @VERIFICA_MOROSO INT
			DECLARE @VERIFICA_MODULO_ANTERIOR_APR INT
			DECLARE @COSTO DECIMAL(10,2)
			DECLARE @COD_MATRICULA int
			

			-- AQUI SE VERIFICA SI EL MODULO ABIERTO ESTA ACTIVO
			SET @VERIFICA_MODULO_ABIERTO = dbo.FN_VERIFICA_MODULO_ABIERTO(@COD_MODULO_ABIERTO)
			-- AQUI SE VERIFICA SI EXISTE CHOQUE DE MATRICULA CON LA NUEVA MATRICULA
			SET @VERIFICA_CHOQUE_MATRICULA = dbo.FN_VERIFICAR_CHOQUES_MATRICULA(@ID_ESTUDIANTE, @COD_MODULO_ABIERTO)
			-- AQUI SE VERIFICA QUE EL ESTUDIANTE NO ESTE MOROSO
			SET @VERIFICA_MOROSO = dbo.FN_VERIFCAR_MOROSO(@ID_ESTUDIANTE)
			-- AQUI SE VERIFICA QUE EL ESTUDIANTE APROVARA EL MODULO ANTERIOR "DE SER NECESARIO"
			SET @VERIFICA_MODULO_ANTERIOR_APR = dbo.FN_VERIFICAR_REQUISITOS_MODULO(@ID_ESTUDIANTE,@COD_MODULO_ABIERTO)

			IF(@VERIFICA_MODULO_ABIERTO=1)
				BEGIN
					SET @MSJ = 'EL MODULO ESTA ACTIVO ES MATRICULABLE'
					PRINT @MSJ
				END
			ELSE
				BEGIN
					SET @MSJ = 'EL MODULO ESTA INACTIVO NO ES MATRICULABLE'
					PRINT @MSJ
				END


			IF(@VERIFICA_CHOQUE_MATRICULA=0)
				BEGIN
					SET @MSJ = 'NO EXISTE CHOQUE,PUEDE MATRICULAR'
					PRINT @MSJ
				END
			ELSE
				BEGIN
					SET @MSJ = 'EXISTE CHOQUE, NO PUEDE MATRICULAR '
					PRINT @MSJ
				END

			IF(@VERIFICA_MOROSO=0)
				BEGIN
					SET @MSJ = 'NO ESTA MOROSO Y PUEDE MATRICULAR'
					PRINT @MSJ
				END
			ELSE
				BEGIN
					SET @MSJ = 'ESTA MOROSO Y NO PUEDE MATRICULAR'
					PRINT @MSJ
				END

			IF(@VERIFICA_MODULO_ANTERIOR_APR=1)
				BEGIN
					SET @MSJ = 'CUMPLE EL REQUISITO O NO TIENE REQUISITO Y PUEDE MATRICULAR'
					PRINT @MSJ
				END
			ELSE
				BEGIN
					SET @MSJ = 'NO CUMPLE EL REQUISITO, NO PUEDE MATRICULAR '
					PRINT @MSJ
				END
			
						
			IF(@VERIFICA_MODULO_ABIERTO=1 AND @VERIFICA_CHOQUE_MATRICULA=0 AND @VERIFICA_MOROSO=0 AND @VERIFICA_MODULO_ANTERIOR_APR=1)
				BEGIN					
					SET @COSTO =(SELECT COSTO
								FROM MODULOS_ABIERTOS MA
								INNER JOIN MODULOS_PROGRAMAS MP
								ON MA.COD_MODULO_PROGRAMA=MP.COD_MODULO_PROGRAMA
								INNER JOIN MODULOS M
								ON MP.COD_MODULO=M.COD_MODULO
								WHERE MA.COD_MODULO_ABIERTO = @COD_MODULO_ABIERTO)

					INSERT INTO MATRICULAS(ID_ESTUDIANTE,TOTAL_MATRICULA,TOTAL_PAGADO) 
							VALUES(@ID_ESTUDIANTE ,@COSTO,@TOTAL_PAGADO)

					SET @COD_MATRICULA = IDENT_CURRENT('MATRICULAS')

					INSERT INTO DETALLES_MATRICULAS(COD_MATRICULA,COD_MODULO_ABIERTO)
						VALUES(@COD_MATRICULA,@COD_MODULO_ABIERTO)					
					SET @MSJ='SE MATRICULA CORRECTAMENTE'					
				END
			ELSE
				BEGIN
					SET @MSJ='MATRICULA FALLO'
				END
		COMMIT TRAN
	END TRY
	BEGIN CATCH		
		ROLLBACK
		SET @MSJ = ERROR_MESSAGE()
	END CATCH
GO


--SELECT*FROM MATRICULAS
--SELECT*FROM DETALLES_MATRICULAS
--SELECT*FROM MODULOS
--SELECT*FROM MODULOS_PROGRAMAS
--SELECT*FROM MODULOS_ABIERTOS


--GO
--DECLARE @ID_ESTUDIANTE varchar(9) = '206730045'
--DECLARE @COD_MODULO_ABIERTO int = 8 
--DECLARE @TOTAL_PAGADO decimal(10,2) = 170000
--DECLARE @MSJ varchar(1000)

---- TODO: Set parameter values here.

--EXECUTE  [dbo].[SP_MATRICULAR] 
--   @ID_ESTUDIANTE
--  ,@COD_MODULO_ABIERTO
--  ,@TOTAL_PAGADO
--  ,@MSJ OUTPUT
--  PRINT @MSJ
--GO

--(SELECT COSTO
--FROM MODULOS_ABIERTOS MA
--INNER JOIN MODULOS_PROGRAMAS MP
--ON MA.COD_MODULO_PROGRAMA=MP.COD_MODULO_PROGRAMA
--INNER JOIN MODULOS M
--ON MP.COD_MODULO=M.COD_MODULO
--WHERE MA.COD_MODULO_ABIERTO = 8)





----------------------------------------------------------------------------------------------------










----ESTE QUERTY ME DICE LO QUE TIENE MATRICULADO
--SELECT M.COD_MATRICULA,DM.COD_DETALLE_MATRICULA,E.ID_ESTUDIANTE,NOMBRE_ESTUDIANTE,MA.COD_MODULO_ABIERTO,MP.REQUISITO,MO.NOMBRE_MODULO,M.ESTADO_FACTURA,M.TOTAL_MATRICULA,M.TOTAL_PAGADO,H.DIA,H.HORA_INICIO,H.HORA_FIN
--FROM ESTUDIANTES E INNER JOIN MATRICULAS M
--ON E.ID_ESTUDIANTE=M.ID_ESTUDIANTE
--INNER JOIN DETALLES_MATRICULAS DM
--ON M.COD_MATRICULA=DM.COD_MATRICULA
--INNER JOIN MODULOS_ABIERTOS MA
--ON DM.COD_MODULO_ABIERTO=MA.COD_MODULO_ABIERTO
--INNER JOIN MODULOS_PROGRAMAS MP
--ON MA.COD_MODULO_PROGRAMA=MP.COD_MODULO_PROGRAMA
--INNER JOIN MODULOS MO
--ON MP.COD_MODULO=MO.COD_MODULO
--INNER JOIN HORARIOS H
--ON H.COD_MODULO_ABIERTO=MA.COD_MODULO_ABIERTO
--WHERE E.ID_ESTUDIANTE='206730045'

--SELECT*FROM MATRICULAS

----ESTE QUERTY ES PARA VER LOS MODULOS ABIERTOS Y SUS HORARIOS
--SELECT MA.COD_MODULO_ABIERTO,MO.NOMBRE_MODULO,MP.REQUISITO,H.DIA,H.HORA_INICIO,H.HORA_FIN
--FROM MODULOS_ABIERTOS MA 
--INNER JOIN MODULOS_PROGRAMAS MP
--ON MA.COD_MODULO_PROGRAMA=MP.COD_MODULO_PROGRAMA
--INNER JOIN MODULOS MO
--ON MO.COD_MODULO=MP.COD_MODULO
--INNER JOIN HORARIOS H
--ON H.COD_MODULO_ABIERTO=MA.COD_MODULO_ABIERTO



--SELECT E.NOMBRE_ESTUDIANTE,E.ID_ESTUDIANTE,RE.NOTA_ESTUDIANTE,RE.ESTADO
--FROM  REGISTRO_NOTAS_ESTUDIANTES RE
--INNER JOIN ESTUDIANTES E
--ON RE.ID_ESTUDIANTE=E.ID_ESTUDIANTE



--SELECT*FROM MODULOS_ABIERTOS
--SELECT*FROM DETALLES_MATRICULAS

--EXEC VERFICAR_CHOQUE_HORARIO '206730045', 3
	
	



----------------------------------------------------------------------------------
GO
CREATE OR ALTER PROCEDURE SP_MOSTRAR_MATERIAS_ABIERTAS
AS
	BEGIN TRY
		BEGIN TRAN
				--ESTE QUERTY ES PARA VER LOS MODULOS ABIERTOS Y SUS HORARIOS
				SELECT MA.COD_MODULO_ABIERTO,P.NOMBRE_PROGRAMA,MO.NOMBRE_MODULO,MO.COSTO,MO.HORAS_TOTALES,MP.REQUISITO,H.DIA,H.HORA_INICIO,H.HORA_FIN
				FROM MODULOS_ABIERTOS MA 
				INNER JOIN MODULOS_PROGRAMAS MP
				ON MA.COD_MODULO_PROGRAMA=MP.COD_MODULO_PROGRAMA
				INNER JOIN MODULOS MO
				ON MO.COD_MODULO=MP.COD_MODULO
				INNER JOIN HORARIOS H
				ON H.COD_MODULO_ABIERTO=MA.COD_MODULO_ABIERTO
				INNER JOIN PROGRAMAS P
				ON P.COD_PROGRAMA=MP.COD_PROGRAMA
				WHERE MA.ESTADO = 'ACT'

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK
	END CATCH
GO
-- TODO: Set parameter values here.

--EXECUTE [dbo].[SP_MOSTRAR_MATERIAS_ABIERTAS] 
--GO


GO
CREATE OR ALTER FUNCTION FN_VERIFICAR_CHOQUES_HORARIO_PROFESOR (@ID_PROFESOR VARCHAR(9), @COD_MODULO_ABIERTO INT)
RETURNS int 
AS
	BEGIN
	DECLARE @EXISTE_CHOQUE int

		--Declaramos las siguientes variables para analizar el choque de horario.    
	DECLARE @FECHA_INICIO TIME, @FECHA_FIN TIME, @DIA varchar(1)    
--Declarmos un CURSOR para recorrer los registros del query siguiente.    
	DECLARE C_HORARIOS_MATERIA_MATRICULAR 
	CURSOR FOR
--Con este query vamos a extraer los horarios y el dia de la materia que el estudiante quiere matricular de la tabla HORARIOS.    
	SELECT        
	HORA_INICIO,
	HORA_FIN,
	DIA 
    FROM HORARIOS
    WHERE COD_MODULO_ABIERTO = @COD_MODULO_ABIERTO   
	--Abrimos cursor     
	OPEN C_HORARIOS_MATERIA_MATRICULAR
    --Recuperar informacion sobre el primer registro
	
	FETCH C_HORARIOS_MATERIA_MATRICULAR INTO @FECHA_INICIO, @FECHA_FIN, @DIA    
	--Iteramos los registros    
	WHILE (@@FETCH_STATUS = 0)        
	BEGIN            
	--En este query lo que hace es verificar si ya exite algun horario del estudiante que haga match con el horario de la materia que quiere matricular
		IF EXISTS (                
			SELECT 1
			FROM MODULOS_ABIERTOS MA
			INNER JOIN PROFESORES P
			ON MA.ID_PROFESOR=P.ID_PROFESOR
			INNER JOIN HORARIOS H
			ON MA.COD_MODULO_ABIERTO=H.COD_MODULO_ABIERTO
			WHERE P.ID_PROFESOR = @ID_PROFESOR
			AND H.DIA = @DIA
			AND(HORA_INICIO <=@FECHA_FIN AND HORA_FIN >=@FECHA_INICIO))
			

			BEGIN
				SET @EXISTE_CHOQUE=1	-- EXISTE CHOQUE		
			END
        ELSE 
            BEGIN  
				SET @EXISTE_CHOQUE=0     -- NO EXISTE CHOQUE				
			END
        --Continuar con el siguiente registro                   
		FETCH C_HORARIOS_MATERIA_MATRICULAR INTO @FECHA_INICIO, @FECHA_FIN, @DIA        
		END
    --Cerrar el CURSOR
	CLOSE C_HORARIOS_MATERIA_MATRICULAR
    --Liberar el CURSOR
	DEALLOCATE C_HORARIOS_MATERIA_MATRICULAR	
	RETURN @EXISTE_CHOQUE
	END
GO
--------------------------------------------------------------------------------
GO
CREATE OR ALTER FUNCTION FN_VERFICAR_CERTIFICADO(@ID_PROFESOR VARCHAR(9), @COD_MODULO_ABIERTO INT)
RETURNS INT
AS
	BEGIN
	DECLARE @RESULTADO INT
	DECLARE @NOMBRE_MODULO VARCHAR(100)
	DECLARE @NOMBRE_CETIFICADO VARCHAR(100)

	SET @NOMBRE_CETIFICADO=(SELECT CP.NOMBRE_CERTIFICACION			
							FROM MODULOS M
							INNER JOIN MODULOS_PROGRAMAS MP
							ON M.COD_MODULO=MP.COD_MODULO
							INNER JOIN MODULOS_ABIERTOS MA
							ON MP.COD_MODULO_PROGRAMA=MA.COD_MODULO_PROGRAMA
							INNER JOIN PROFESORES P
							ON MA.ID_PROFESOR=P.ID_PROFESOR
							INNER JOIN CERTIFICACIONES_PROFESORES CP
							ON P.ID_PROFESOR=CP.ID_PROFESOR
							WHERE P.ID_PROFESOR=@ID_PROFESOR)
			--------------------------------
	    SET @NOMBRE_MODULO=(SELECT M.NOMBRE_MODULO
							FROM MODULOS M
							INNER JOIN MODULOS_PROGRAMAS MP
							ON M.COD_MODULO=MP.COD_MODULO
							INNER JOIN MODULOS_ABIERTOS MA
							ON MP.COD_MODULO_PROGRAMA=MA.COD_MODULO_PROGRAMA							
							WHERE MA.COD_MODULO_ABIERTO=@COD_MODULO_ABIERTO)


			IF (@NOMBRE_CETIFICADO=@NOMBRE_MODULO)
				BEGIN
					SET @RESULTADO=1 --PUEDE DAR EL MODULO
				END
			ELSE
				BEGIN
					SET @RESULTADO=0 -- NO PUEDE DAR EL MODULO
				END

		RETURN @RESULTADO
	END
GO


--SELECT*FROM PROFESORES


--DECLARE @RESULTADO INT
--DECLARE @ID_PROFESOR VARCHAR(9) = '222222000'
--DECLARE @COD_MODULO_ABIERTO INT = 6
--SET @RESULTADO = dbo.FN_VERFICAR_CERTIFICADO(@ID_PROFESOR, @COD_MODULO_ABIERTO)
--PRINT @RESULTADO
----------------------------------------------


--DECLARE @DIA varchar(1)='M'
--DECLARE @HORA_INICIO time(7)='07:00:00.0000000'
--DECLARE @HORA_FIN time(7)='12:00:00.0000000'
--DECLARE @ID_PROFESOR varchar(9)= '222222000'
--DECLARE @NUMERO_LABORATORIO int = 1
--DECLARE @COD_MODULO_PROGRAMA int = 6
--DECLARE @FECHA_INICIO date = '20230220'
--DECLARE @MSJ varchar(1000) 

---- TODO: Set parameter values here.

--EXECUTE [dbo].[SP_ABRIR_MODULO] 
--   @DIA
--  ,@HORA_INICIO
--  ,@HORA_FIN
--  ,@ID_PROFESOR
--  ,@NUMERO_LABORATORIO
--  ,@COD_MODULO_PROGRAMA
--  ,@FECHA_INICIO
--  ,@MSJ OUTPUT
--  PRINT @MSJ



-------------------------------------------------------------------------------------------------------

GO
CREATE OR ALTER FUNCTION FN_VERIFICAR_CHOQUE_LABORATORIOS (@NUM_LABORATORIO INT, @COD_MODULO_ABIERTO INT)
RETURNS int 
AS
	BEGIN
	DECLARE @EXISTE_CHOQUE int

		--Declaramos las siguientes variables para analizar el choque de horario.    
	DECLARE @FECHA_INICIO TIME, @FECHA_FIN TIME, @DIA varchar(1)    
--Declarmos un CURSOR para recorrer los registros del query siguiente.    
	DECLARE C_HORARIOS_MATERIA_MATRICULAR 
	CURSOR FOR
--Con este query vamos a extraer los horarios y el dia de la materia que el estudiante quiere matricular de la tabla HORARIOS.    
	SELECT        
	HORA_INICIO,
	HORA_FIN,
	DIA 
    FROM HORARIOS
    WHERE COD_MODULO_ABIERTO = @COD_MODULO_ABIERTO   
	--Abrimos cursor     
	OPEN C_HORARIOS_MATERIA_MATRICULAR
    --Recuperar informacion sobre el primer registro
	
	FETCH C_HORARIOS_MATERIA_MATRICULAR INTO @FECHA_INICIO, @FECHA_FIN, @DIA    
	--Iteramos los registros    
	WHILE (@@FETCH_STATUS = 0)        
	BEGIN            
	--En este query lo que hace es verificar si ya exite algun horario del estudiante que haga match con el horario de la materia que quiere matricular
		IF EXISTS (                
			SELECT 1
			FROM LABORATORIOS L
			INNER JOIN MODULOS_ABIERTOS MA
			ON L.COD_MODULO_ABIERTO=MA.COD_MODULO_ABIERTO
			INNER JOIN HORARIOS H
			ON MA.COD_MODULO_ABIERTO=H.COD_MODULO_ABIERTO
			WHERE L.LABORATORIO_NUMERO = @NUM_LABORATORIO
			AND H.DIA = @DIA
			AND(HORA_INICIO <=@FECHA_FIN AND HORA_FIN >=@FECHA_INICIO))
			

			BEGIN
				SET @EXISTE_CHOQUE=1	-- EXISTE CHOQUE		
			END
        ELSE 
            BEGIN  
				SET @EXISTE_CHOQUE=0     -- NO EXISTE CHOQUE				
			END
        --Continuar con el siguiente registro                   
		FETCH C_HORARIOS_MATERIA_MATRICULAR INTO @FECHA_INICIO, @FECHA_FIN, @DIA        
		END
    --Cerrar el CURSOR
	CLOSE C_HORARIOS_MATERIA_MATRICULAR
    --Liberar el CURSOR
	DEALLOCATE C_HORARIOS_MATERIA_MATRICULAR	
	RETURN @EXISTE_CHOQUE
	END
GO


--DECLARE @RESULTADO INT
--DECLARE @NUM_LABORATORIO INT = 1
--DECLARE @COD_MODULO_ABIERTO INT = 10
--SET @RESULTADO = dbo.FN_VERIFICAR_CHOQUE_LABORATORIOS( @NUM_LABORATORIO, @COD_MODULO_ABIERTO)
--PRINT @RESULTADO

--GO


		
----MUESTRA LOS PROFESORES Y LAS CLASES QUE DAN
--SELECT P.ID_PROFESOR,P.NOMBRE_PROFESOR,MA.COD_MODULO_ABIERTO,MP.COD_MODULO,M.NOMBRE_MODULO,H.DIA,H.HORA_INICIO,H.HORA_FIN
--FROM MODULOS_ABIERTOS MA
--INNER JOIN PROFESORES P
--ON MA.ID_PROFESOR=P.ID_PROFESOR
--INNER JOIN HORARIOS H
--ON MA.COD_MODULO_ABIERTO=H.COD_MODULO_ABIERTO
--INNER JOIN MODULOS_PROGRAMAS MP
--ON MP.COD_MODULO_PROGRAMA= MA.COD_MODULO_PROGRAMA
--INNER JOIN MODULOS M
--ON M.COD_MODULO=MP.COD_MODULO



		
--SELECT P.ID_PROFESOR,P.NOMBRE_PROFESOR,CP.NOMBRE_CERTIFICACION
--FROM PROFESORES P
--INNER JOIN CERTIFICACIONES_PROFESORES CP
--ON P.ID_PROFESOR=CP.ID_PROFESOR





GO



----------------------------------------------------------------------------------------
CREATE OR ALTER FUNCTION FN_FECHA_FINAL(@HORAS_TOTALES INT,@FECHA_INICIO date )
RETURNS date
AS
	BEGIN
			DECLARE @FECHAAUX DATE 
			DECLARE @CONT INT = 8			
			DECLARE @DIA varchar(20)

			SELECT  @DIA =  (case DATEPART(dw,DATEADD(DAY,1,@FECHA_INICIO)) when 2 then 'Lunes' when 3 -- VERIFICAR SINO ES SABADO O DOMINGO
				then 'Martes' when 4 then 'Miércoles' when 5 then 'Jueves' when 6 then 'Viernes' 
				when 7 then 'Sábado' when 1 then 'Domingo' end) 
				--PRINT @DIA
				IF (@DIA<>'Sábado' AND @DIA<>'Domingo') --SI ES DIFERENTE SABADO O DOMINGO
					BEGIN
		
						SET @FECHAAUX = @FECHA_INICIO
						WHILE @HORAS_TOTALES>=0
							BEGIN				
								SET @FECHAAUX = ( SELECT DATEADD(DAY,@CONT,@FECHAAUX))				
								IF NOT EXISTS(SELECT 1 FROM FERIADOS WHERE FECHA_CELEBRACION = @FECHAAUX)
									BEGIN						  
										SET @HORAS_TOTALES=@HORAS_TOTALES-5
									END				
							END
					END					
					--PRINT @FECHAAUX
		RETURN @FECHAAUX
	END
GO

--DECLARE @RESULTADO date
--DECLARE @HORAS_TOTALES INT = 250
--DECLARE @FECHA_INICIO date = '20230221'
--SET @RESULTADO = dbo.FN_FECHA_FINAL( @HORAS_TOTALES, @FECHA_INICIO)
--PRINT @RESULTADO

--GO



--------------------------------------------------------------------------------
GO
CREATE OR ALTER PROCEDURE SP_ABRIR_MODULO (@DIA VARCHAR(1),
											@HORA_INICIO TIME,
											@HORA_FIN TIME,
											@ID_PROFESOR varchar(9),
											@NUMERO_LABORATORIO int,
											@COD_MODULO_PROGRAMA int,
											@FECHA_INICIO date,
											@MSJ varchar(1000)OUT)

AS
	BEGIN TRY
		BEGIN TRAN
			DECLARE @VERIFICAR_CERTIFICADO int
			DECLARE @VERIFICAR_CHOQUE_HORARIO_PROFESOR int
			DECLARE @VERIFICAR_CHOQUE_HORARIO_LABORATORIO int
			DECLARE @FECHA_FINAL date
			DECLARE @HORAS_TOTALES int
			DECLARE @COD_MODULO_ABIERTO int
			
						INSERT INTO MODULOS_ABIERTOS(ID_PROFESOR,COD_MODULO_PROGRAMA,FECHA_INICIO)
					VALUES(@ID_PROFESOR,@COD_MODULO_PROGRAMA,@FECHA_INICIO)
				
				SET @COD_MODULO_ABIERTO=IDENT_CURRENT('MODULOS_ABIERTOS')

			
					INSERT INTO HORARIOS(COD_MODULO_ABIERTO,HORA_INICIO,HORA_FIN,DIA)
					VALUES(@COD_MODULO_ABIERTO,@HORA_INICIO,@HORA_FIN,@DIA)
			
				
				PRINT @COD_MODULO_ABIERTO
			-- TENGO UN ERROR EN ESTA FUNCION 
			--SET @VERIFICAR_CERTIFICADO = dbo.FN_VERFICAR_CERTIFICADO(@ID_PROFESOR, @COD_MODULO_ABIERTO)
			--IF (@VERIFICAR_CERTIFICADO=1)
			--	BEGIN	
			--		SET @MSJ = 'PUEDE IMPARTIR EL MODULO'
			--		PRINT @MSJ
			--	END
			--ELSE
			--	BEGIN
			--		SET @MSJ = 'NO PUEDE IMPARTIR EL MODULO'
			--		PRINT @MSJ
			--	END

			SET @VERIFICAR_CHOQUE_HORARIO_PROFESOR = dbo.FN_VERIFICAR_CHOQUES_HORARIO_PROFESOR (@ID_PROFESOR , @COD_MODULO_ABIERTO)
			IF (@VERIFICAR_CHOQUE_HORARIO_PROFESOR = 1)
				BEGIN	
					SET @MSJ = 'EXISTE CHOQUE HORARIOS PROFESOR'
					PRINT @MSJ
				END
			ELSE
				BEGIN
					SET @MSJ = 'NO EXISTE CHOQUE HORARIOS PROFESOR'
					PRINT @MSJ
				END


			 SET @VERIFICAR_CHOQUE_HORARIO_LABORATORIO = dbo.FN_VERIFICAR_CHOQUE_LABORATORIOS(@NUMERO_LABORATORIO , @COD_MODULO_ABIERTO)
				IF (@VERIFICAR_CHOQUE_HORARIO_LABORATORIO = 1)
				BEGIN	
					SET @MSJ = 'EXISTE CHOQUE LABORATORIOS'
					PRINT @MSJ
				END
			ELSE
				BEGIN
					SET @MSJ = 'NO EXISTE CHOQUE LABORATORIOS'
					PRINT @MSJ
				END

				SET @HORAS_TOTALES= (SELECT M.HORAS_TOTALES
									FROM MODULOS_ABIERTOS MA
									INNER JOIN MODULOS_PROGRAMAS MP
									ON MA.COD_MODULO_PROGRAMA=MP.COD_MODULO_PROGRAMA
									INNER JOIN MODULOS M
									ON MP.COD_MODULO=M.COD_MODULO
									WHERE COD_MODULO_ABIERTO=@COD_MODULO_ABIERTO)

			SET	@FECHA_FINAL=dbo.FN_FECHA_FINAL(@HORAS_TOTALES,@FECHA_INICIO)
			IF (@FECHA_FINAL IS NULL)
				BEGIN	
					SET @MSJ = 'NO SE PUDO INSERTAR PORQUE NO HAY FECHA FINAL, INTENTELO DE NUEVO'
					PRINT @MSJ
				END
			ELSE
				BEGIN
					SET @MSJ = 'FECHA CORRECTA'
					PRINT @MSJ
				END

			IF(@VERIFICAR_CERTIFICADO<>1 AND @VERIFICAR_CHOQUE_HORARIO_PROFESOR<> 0 AND @VERIFICAR_CHOQUE_HORARIO_LABORATORIO <> 0 AND @FECHA_FINAL IS NULL )
				BEGIN
					set @MSJ = 'LA MATERIA NO PUEDE SER ABIERTA'
					RAISERROR(@MSJ,16,2)	
				END
			ELSE
				BEGIN
					UPDATE MODULOS_ABIERTOS SET FECHA_FIN = @FECHA_FINAL WHERE COD_MODULO_ABIERTO = @COD_MODULO_ABIERTO					
				END

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK
		set @MSJ = ERROR_MESSAGE()
	END CATCH

GO

----------------------------------------------------------------------------------


--GO
--DECLARE @DIA varchar(1)='J'
--DECLARE @HORA_INICIO time(7)='07:00:00.0000000'
--DECLARE @HORA_FIN time(7)='12:00:00.0000000'
--DECLARE @ID_PROFESOR varchar(9)= '222222000'
--DECLARE @NUMERO_LABORATORIO int = 1
--DECLARE @COD_MODULO_PROGRAMA int = 6
--DECLARE @FECHA_INICIO date = '20230220'
--DECLARE @MSJ varchar(1000) 

---- TODO: Set parameter values here.

--EXECUTE [dbo].[SP_ABRIR_MODULO] 
--   @DIA
--  ,@HORA_INICIO
--  ,@HORA_FIN
--  ,@ID_PROFESOR
--  ,@NUMERO_LABORATORIO
--  ,@COD_MODULO_PROGRAMA
--  ,@FECHA_INICIO
--  ,@MSJ OUTPUT
--  PRINT @MSJ
--GO

--SELECT*FROM MODULOS_ABIERTOS
--SELECT*FROM HORARIOS





-------------------------------------------------------------------------------------

----ME MUESTRA 
--SELECT P.ID_PROFESOR, P.NOMBRE_PROFESOR,M.NOMBRE_MODULO,L.LABORATORIO_NUMERO,M.COD_MODULO,L.COD_MODULO_ABIERTO,H.DIA,H.HORA_INICIO,H.HORA_FIN 
--FROM LABORATORIOS L
--INNER JOIN MODULOS_ABIERTOS MA
--ON L.COD_MODULO_ABIERTO=MA.COD_MODULO_ABIERTO
--INNER JOIN HORARIOS H
--ON MA.COD_MODULO_ABIERTO=H.COD_MODULO_ABIERTO
--INNER JOIN MODULOS_PROGRAMAS MP
--ON MP.COD_MODULO_PROGRAMA=MA.COD_MODULO_PROGRAMA
--INNER JOIN MODULOS M
--ON MP.COD_MODULO=M.COD_MODULO
--INNER JOIN PROFESORES P
--ON P.ID_PROFESOR=MA.ID_PROFESOR
